// Read Something Together — pick data
// Each pick must offer something to BOTH August and Julia (see ../selection-criteria.md).
// lean: 'a' = leans August, 'j' = leans Julia, 'b' = squarely both.
// Quotes are kept to a single short line or omitted.

const PICKS = [
  {
    n: 1,
    title: "Tlön, Uqbar, Orbis Tertius",
    author: "Jorge Luis Borges",
    venue: "Sur",
    year: 1940,
    url: "https://sites.evergreen.edu/politicalshakespeares/wp-content/uploads/sites/226/2015/12/Borges-Tl%C3%B6n-Uqbar-Orbius-Tertius.pdf",
    mins: 30,
    kind: "fiction",
    lean: "b",
    added: "2026-07-12",
    note: "The ur-text of cerebral weird fiction: a conspiracy of scholars invents an encyclopedia of a fictional world, and the invented world starts colonizing the real one. Julia gets the strangest, most elegant story ever built out of footnotes and mirrors. August gets something eerier — a 1940 case study of how a sufficiently coherent information system doesn't describe reality, it replaces it. Read it and then think about training data.",
    quote: ""
  },
  {
    n: 2,
    title: "Frank Sinatra Has a Cold",
    author: "Gay Talese",
    venue: "Esquire",
    year: 1966,
    url: "https://www.esquire.com/news-politics/a638/frank-sinatra-has-a-cold-gay-talese/",
    mins: 55,
    kind: "journalism",
    lean: "j",
    added: "2026-07-12",
    note: "The most celebrated magazine profile ever written — and Sinatra never gave Talese an interview. For Julia: this is the piece that invented modern long-form journalism, assembled entirely from the edges of a subject. For August: it's a cold-eyed study of power, entourage, and image management — a Succession episode set in 1965, complete with the terrified courtiers.",
    quote: "Sinatra with a cold is Picasso without paint, Ferrari without fuel — only worse."
  },
  {
    n: 3,
    title: "How to Be Good",
    author: "Larissa MacFarquhar",
    venue: "The New Yorker",
    year: 2011,
    url: "https://www.newyorker.com/magazine/2011/09/05/how-to-be-good",
    mins: 50,
    kind: "profile",
    lean: "j",
    added: "2026-07-12",
    note: "A profile of Derek Parfit, the analytic philosopher who spent his life on personal identity and what we owe the future, written with novelistic strangeness. Julia: this is your tradition's greatest eccentric, rendered as an unforgettable character. August: Parfit's view — that identity over time is just psychological continuity, and matters less than we think — is the Severance problem stated formally. What do you owe your innie?",
    quote: ""
  },
  {
    n: 4,
    title: "On the Phenomenon of Bullshit Jobs",
    author: "David Graeber",
    venue: "Strike! Magazine",
    year: 2013,
    url: "https://strikemag.org/bullshit-jobs/",
    mins: 12,
    kind: "essay",
    lean: "b",
    added: "2026-07-12",
    note: "An anthropologist asks why capitalism, which is supposed to hate waste, generates millions of jobs that even the people doing them believe are pointless. Short, furious, and very funny. This is the Lumon Industries thesis statement — sociology of work for August, corporate absurdism Julia can bill 0.3 hours to reading.",
    quote: "It's as if someone were out there making up pointless jobs just for the sake of keeping us all working."
  },
  {
    n: 5,
    title: "Meditations on Moloch",
    author: "Scott Alexander",
    venue: "Slate Star Codex",
    year: 2014,
    url: "https://slatestarcodex.com/2014/07/30/meditations-on-moloch/",
    mins: 55,
    kind: "essay",
    lean: "a",
    added: "2026-07-12",
    note: "A sprawling weird think piece that starts as a close reading of Ginsberg's 'Howl' and becomes a demonology of coordination failure — why systems reliably produce outcomes nobody in them wants. August: this essay quietly underwrites half of modern AI-policy discourse; you've been in meetings that are secretly about it. Julia: it's structured like scriptural exegesis and reads like analytic philosophy having a nervous breakdown, in the best way.",
    quote: "The opposite of a trap is a garden."
  },
  {
    n: 6,
    title: "The Sucker, the Sucker!",
    author: "Amia Srinivasan",
    venue: "London Review of Books",
    year: 2017,
    url: "https://www.lrb.co.uk/the-paper/v39/n17/amia-srinivasan/the-sucker-the-sucker",
    mins: 25,
    kind: "essay",
    lean: "b",
    added: "2026-07-12",
    note: "An Oxford analytic philosopher reviews two books about octopuses and produces the best essay ever written on what it's like to be a mind utterly unlike ours. Julia gets rigorous philosophy of mind in gorgeous prose; August gets first-contact-grade science writing about the only alien intelligence we've actually met. The title alone earns its place.",
    quote: ""
  },
  {
    n: 7,
    title: "Escape from Spiderhead",
    author: "George Saunders",
    venue: "The New Yorker",
    year: 2010,
    url: "https://www.newyorker.com/magazine/2010/12/20/escape-from-spiderhead",
    mins: 45,
    kind: "fiction",
    lean: "b",
    added: "2026-07-12",
    note: "In a corporate research facility, prisoners test emotion-altering drugs administered by cheerful technicians speaking flawless HR. Unsettling, hilarious, and then quietly shattering — Severance before Severance existed, with Ex Machina's ethics-of-the-lab dread. Saunders is the great American writer of institutional language used to launder cruelty; you will both recognize the dialect.",
    quote: ""
  },
  {
    n: 8,
    title: "The Friendship That Made Google Huge",
    author: "James Somers",
    venue: "The New Yorker",
    year: 2018,
    url: "https://www.newyorker.com/magazine/2018/12/10/the-friendship-that-made-google-huge",
    mins: 35,
    kind: "profile",
    lean: "a",
    added: "2026-07-12",
    note: "Jeff Dean and Sanjay Ghemawat, who write code together at one keyboard and quietly rebuilt Google's foundations several times over. August: the best mainstream account of what world-class engineering actually feels like from inside. Julia: it's secretly a tender double profile about a decades-long friendship — the rare tech story where the humans are the interesting part.",
    quote: ""
  },
  {
    n: 9,
    title: "The Communal Mind",
    author: "Patricia Lockwood",
    venue: "London Review of Books",
    year: 2019,
    url: "https://www.lrb.co.uk/the-paper/v41/n04/patricia-lockwood/the-communal-mind",
    mins: 25,
    kind: "essay",
    lean: "j",
    added: "2026-07-12",
    note: "Lockwood reports from inside 'the portal' — the internet — in fragments that are half prose-poem, half fever dream, and funnier than either has any right to be. Julia: this is the weird think piece perfected, unsettling in the way good weird fiction is. August: no one has better captured the texture of the communal machine-mind we all now partly live in — futurism by immersion rather than prediction.",
    quote: ""
  },
  {
    n: 10,
    title: "Exhalation",
    author: "Ted Chiang",
    venue: "Lightspeed Magazine",
    year: 2008,
    url: "https://www.lightspeedmagazine.com/fiction/exhalation/",
    mins: 30,
    kind: "fiction",
    lean: "b",
    added: "2026-07-12",
    note: "A scientist in a universe of air-driven mechanical beings performs an auto-dissection of his own brain and discovers what powers thought — and what must eventually happen to it. Philosophy of mind as jewel-box fable: Julia gets a thought experiment worthy of the analytic canon, August gets the finest working sci-fi writer at his absolute peak. Quietly devastating and strangely consoling at once.",
    quote: "Contemplate the marvel that is existence, and rejoice that you are able to do so."
  },
  {
    n: 11,
    title: "Lena",
    author: "qntm",
    venue: "qntm.org",
    year: 2021,
    url: "https://qntm.org/mmacevedo",
    mins: 10,
    kind: "fiction",
    lean: "b",
    added: "2026-07-12",
    note: "A Wikipedia article from a future where the first successfully scanned human brain has become a widely-forked piece of software with 'workload attitude problems.' Two thousand words of encyclopedic deadpan that add up to the most quietly horrifying AI story ever written — Severance's innie problem taken to its logical end. You will both think about this one for weeks; August may also think about it at work.",
    quote: ""
  },
  {
    n: 12,
    title: "Nobody Here Wants the Data Center: An Oral History",
    author: "J.J. Anselmi",
    venue: "The New Republic",
    year: 2026,
    url: "https://newrepublic.com/article/211363/ai-data-center-oral-history",
    mins: 20,
    kind: "journalism",
    lean: "a",
    added: "2026-07-12",
    note: "What happens when the AI buildout lands in your town, told chorus-style by the neighbors: the noise, the water, the tax deals, the meetings where nobody's questions get answered. August: the material politics of compute, uncomfortably close to the day job. Julia: oral-history long-form with the mounting dread of a good horror story — except the monster is a substation. Fresh from June 2026.",
    quote: ""
  }
];
